### ISSUE TITLE
What is everybody going to be working on?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-code-sprint-2021-05#1]
Post a comment letting us know what you are going to be working on.

**Comment by pomakis** [comment]
CubeWerx has implemented the majority of the Maps, Tiles and Styles specifications.  However, a lot of the implementation conforms not so much to the draft specifications themselves, but to the tentative alternative way forward for many of the endpoints as proposed by "https://github.com/opengeospatial/ogcapi-maps/issues/56".  CubeWerx's goal in this sprint is to help finalise the way forward in these matters.

Our current implementation is available at "https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa".  This implementation can be adjusted (within reason) during the sprint to explore various approaches.

**Comment by cportele** [comment]
We will provide a Styles server that implements the latest draft, likely as an update to https://demo.ldproxy.net/. If any issues are reported during the sprint, I will try to fix them. 

Since I am the editor of the Styles spec, I will monitor the discussions related to the Styles spec.

In addition, I hope to work on updating the Tiles implementation of [ldproxy](https://github.com/interactive-instruments/ldproxy) to the latest draft.

**Comment by rowanwins** [comment]
I'll probably take a look at some client-side implementations for supporting Tiles and Maps using mapbox-gl/maplibre-gl.

I'm also interested to explore if there is a map-library agnostic way to make a small-ish javascript package for simplifying common operations for things other requesting the actual tiles, eg getting a list/nested list of available maps/layers, listing styles, getting a legend for a style etc. I guess I'm thinking about the sorts of things that you might also find on a map-related UI that someone might be putting together (eg they want to populate a list or table with all the available map options so the user can select one).

**Comment by doublebyte1** [comment]
@PascalLike and myself will have a look at Maps and Tiles server and client side implementations, to serve and consume neuroscience research data.

**Comment by aaime** [comment]
Refresh GeoServer Tiles, Styles and Maps implementations to the latest version of the standards, while offering some data from both sponsors.

**Comment by tinoks** [comment]
Haven't seen any Nodejs implementations. So I will be making an Fastify-based application that autogenerates the routes from a OpenAPI schema. Storage will properly be a SpatiaLite file.

**Comment by pvgenuchten** [comment]
@thijsbrentjens @justb4 and me are preparing a deployment environment for a series of products implementing the OGC API set of standards in the scope of an OGC API testbed with a focus on a number Dutch/European use cases, such as INSPIRE and the Dutch API guidelines. Currently in scope are pygeoapi, ldproxy and geoserver. The repo is available at https://github.com/Geonovum/ogc-api-testbed. Check out the wiki for potential OGC API use cases. Let us know if you have ideas or want to contribute

**Comment by ghobona** [comment]
I will extend the Executable Test Suite of OGC API - Tiles to support more of the conformance class(es) indicated on the attached image.

![ETS_Sprint](https://user-images.githubusercontent.com/18121038/119735160-da6c9e00-be73-11eb-84f4-b79f3ec27390.png)

**Comment by tinoks** [comment]
> > Haven't seen any Nodejs implementations. So I will be making an Fastify-based application that autogenerates the routes from a OpenAPI schema. Storage will properly be a SpatiaLite file.
> 
> @tinoks did you make any progress on this? I would be looking forward to seeing your demo :-)

I have made a repository [here](https://github.com/KORTxyz/ogcapi-spatialite).
