### ISSUE TITLE
Sprint goals - OGC API Styles

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-code-sprint-2021-05#15]
The main goals for the sprint from the perspective of the OGC API Styles working group are:

* Get implementation feedback from client and server implementations on the latest draft of the specification. From those that are upgrading an existing implementation we are also interested in feedback on changes to the specification.
* Test how the API building blocks of Styles, Tiles and Maps fit together.
* We would like to use the sprint to make progress on the following open issues:
  * How to identify that a style can be applied to a data resource? There is a proposal to establish a register of "well-known" types of data distributions that data publishers and style publishers can use to tag their data distributions or styles so that users have a simple mechanism to identify styles and data that can be combined. [Link to Issue](https://github.com/opengeospatial/NamingAuthority/issues/97).
  * There are two different approaches how SLD is used by implementations and the issue includes a proposal how to change the specification to better support SLD as an encoding. This is also linked to the fact that there are different approaches to organising styles, layers and data sources. [Link to Issue](https://github.com/opengeospatial/ogcapi-styles/issues/5).
  * Some of the information in the style metadata can and should be derived automatically (e.g., the list of stylesheets, the self/alternate links). Currently the specification implies that a PUT on the style metadata resource will replace the existing metadata, which easily can lead to problems. Should servers ignore information in the metadata PUT requests that is derived by the server or should we only support PATCH? [Link to Issue](https://github.com/opengeospatial/ogcapi-styles/issues/3).

**Comment by pomakis** [comment]
Regarding SLD, it seems to me that the most natural SLD representation for each of the style enpoints is:

### /styles

An sld:StyledLayerDescriptor that provides a NamedLayer for each mappable collection. Each NamedLayer can have one or more UserStyles (i.e., full style definitions) and/or NamedStyles (i.e., just a style ID and title).

E.g.:

https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/styles?f=sld&pretty=true

### /styles/{styleId}

An sld:UserStyle that provides a FeatureTypeStyle for each collection it can style. If no style definition is available, an sld:NamedStyle can be returned instead.

E.g.:

https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/styles/Topographic?f=sld11style&pretty=true

Compare this to the uglier:

https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/styles/Topographic?f=sld11&pretty=true

### /collections/{collectionId}/styles

An sld:StyledLayerDescriptor that provides a NamedLayer for the specified collection. The NamedLayer can have one or more UserStyles (i.e., full style definitions) and/or NamedStyles (i.e., just a style ID and title).

E.g.:

https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/collections/SettlementSrf/styles?f=sld11&pretty=true

### /collections/{collectionId}/styles/{styleId}

An sld:UserStyle that provides a FeatureTypeStyle for the specified collection. If no style definition is available, an sld:NamedStyle can be returned instead.

E.g.:

https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/collections/SettlementSrf/styles/Topographic?f=sld11style&pretty=true

Compare this to the uglier:

https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/collections/SettlementSrf/styles/Topographic?f=sld11&pretty=true

**Comment by cportele** [comment]
One issue that was raised in the Gitter chat is that many existing deployments use a different approach - and it would be good to still support those.

Maybe we should have two SLD requirements classes, one for each approach.

**Comment by pomakis** [comment]
The gist of my argument is this:  When the client asks for the definition of a style, it makes sense to return a style object (e.g., a UserStyle), not a list of collections (e.g., a StyledLayerDescriptor).

Having two different SLD requirements classes or utilizing two different Content Types (as the CubeWerx server currently does) to allow for both behaviours wouldn't be ideal, since it would practically mean that clients and servers would have to implement support for *both* in order to maximize interoperability.

**Comment by ghobona** [comment]
**Day 3 of 2021-05 Sprint feedback**

Should we have two conformance classes for the different approaches?

One approach involves having the SLD at the top level. The other approach does not.

Recommendation from sprint participants: There is a need to have two separate conformance classes to support the different paradigms.

Action: @cportele will raise the topic for further discussion in SWG.

**Comment by jerstlouis** [comment]
We can also discuss this at the Styles & Symbology SWG meeting June 16th, 4:30 PM.

Per the [SLD specifications](https://portal.ogc.org/files/?artifact_id=22364), is it even valid to have a UserStyle as the top-level  element? The UserStyle example on page 36 is embedded within a StyledLayerDescriptor object.

I believe it is more important to adopt a single most interoperable way to define single and multi-layer styles, and have clear guidance on how collections are associated with sections of the styles which should be applied to them.

**Comment by pomakis** [comment]
Since I seem to be the only one pushing for a top-level UserStyle approach for the .../styles/{styleId} endpoints, I'm willing to concede in order to avoid having to introduce two separate conformance classes, neither of which technically provides more power of flexibility over the other.

It's likely true that all existing support for SLD expects/requires a top-level StyledLayerDescriptor container.  And I suspect the current SLD specification and schemas technically don't even allow a top-level UserStyle.  (However, I see that as more of a trivial oversight that a corrigendum can rectify if we choose to go in that direction.)
