### ISSUE TITLE
Tiles: geodata query parameter

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-code-sprint-2021-05#32]
I see that the query parameter name was changed from "collections" to "geodata". I think this is really confusing, since values will typically be collection identifiers. At least for the cases where the values will always be collection identifiers, it should be allowed to name the query parameter "collections", not "geodata".

PS: I would have said "always" not "typically", but /req/geodata-selection/query-geodata includes text that seems to say that there are exceptions. I do not really understand what the text in the requirement is trying to say or how this is supposed to work.

**Comment by ghobona** [comment]
**Day 3 of 2021-05 Sprint**

ACTION: @joanma747 to review the Tiles API spec to check use of the 'collections' and 'geodata' terms.

**Comment by joanma747** [comment]
Change applied. We can close the issue

**Comment by pomakis** [comment]
So what's the new URI of the conformance class for this?

**Comment by joanma747** [comment]
http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/geodata   :-)

I was just changing it to "collections" but then you get a conformance response like:
```
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core"
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/collections"
  ]
}
```
But the "common" one has one meaning: "definition of collections (geo and non-geo)" and the "maps" one is "include some collections that are geospatial". I was blocked by this thought and I did not do the change.

Now you will tell me what to do.

**Comment by cportele** [comment]
In Tiles it was `geodata-selection`, maybe change it to `collection-selection` in both Maps and Tiles?

**Comment by pomakis** [comment]
Sure, that works too.

**Comment by joanma747** [comment]
I was confused. To many sprint hours. I have applied that change better now including the conformance class name. Thanks. Gobe, you can close the issue now

**Comment by cportele** [comment]
Since I opened the issue and it has been resolved, I will close it.
